add_newline = true

format = """\
 $os\
 $hostname\
 $line_break\
 $shell\
 $all\
 $direnv\
 $line_break\
 $character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[container]
disabled = true

[character]
success_symbol = "[ó±‰¸](color_fg1)"
error_symbol = "[ó±‰¸](color_red)"
vimcmd_symbol = "[ó±‰¸](color_green)"
vimcmd_visual_symbol = "[ó±‰¸](color_green)"

[line_break]
disabled = false

[hostname]
ssh_only = true
style = 'color_fg1'
ssh_symbol = 'ó°’„ '
format = ' ï‡º  [$ssh_symbol$hostname]($style)'

[shell]
disabled = false
style = 'color_orange'
zsh_indicator =  'zsh ï’‰ '
bash_indicator = 'bash î¯Š '
pwsh_indicator = 'pwsh ï„  '

[os]
disabled = false
style = "color_fg0"
format = "[$symbol $name]($style)"

[os.symbols]
Arch = "ïŒƒ "
Linux = "ï…¼ "
Ubuntu = "ïŒ› "
Debian = "ïŒ† "
Windows = "îœ "
Raspbian = "ïŒ• "
Fedora = "ïŒŠ "
Macos = "ï…¹ "
NixOS = "ïŒ“ "

[git_branch]
symbol = "ï˜ "
style = "color_aqua"

[git_commit]
#tag_symbol = " tag "

[git_status]
style = "color_yellow"
#ahead = ">"
#behind = "<"
#diverged = "<>"
#renamed = "r"
#deleted = "x"

[aws]
symbol = "îŒ½  "
disabled = true

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[directory]
style = "color_green"
read_only = "î‚¢"
truncate_to_repo = false
truncation_length = 2

[docker_context]
symbol = "ïŒˆ  "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "


[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[lua]
symbol = "î˜  "

[memory_usage]
symbol = "ï¡š  "

# [meson]
# symbol = "ï¨¶  "

[nim]
symbol = "ïš¤  "

[nix_shell]
symbol = "ïŒ“  "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ  "

[rlang]
symbol = "ï³’  "

[ruby]
symbol = "î‘ "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[spack]
symbol = "ğŸ…¢ "

[direnv]
disabled = false
format = '[$loaded$allowed $rc_path]($style) '
detect_files = ['.envrc', '.env']
symbol = ''
style = 'bold green'
allowed_msg = ''
not_allowed_msg = 'ï‘¨ '
loaded_msg = 'ï¬ '
unloaded_msg = ''
denied_msg = 'ï‘¨ '

