add_newline = true

format = """\
[â•­â•´](238) [ó°„› ](bold yellow) $env_var\
$all[â•°â”€](238) $character"""

[character]
success_symbol = "[ï„¸ ](bold blue)"
error_symbol = "[ï„¸ ](bold red)"
vimcmd_symbol = "[ï„¸ ](bold green)"
vimcmd_visual_symbol = "[ï„¸ ](bold green)"

[git_commit]
#tag_symbol = " tag "

[git_status]
#ahead = ">"
#behind = "<"
#diverged = "<>"
#renamed = "r"
#deleted = "x"

[aws]
symbol = "îŒ½  "
disabled = true

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[directory]
read_only = " ï ½"
truncation_symbol = "â€¦ "
truncate_to_repo = false

[docker_context]
symbol = "ïŒˆ  "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[lua]
symbol = "î˜  "

[memory_usage]
symbol = "ï¡š  "

# [meson]
# symbol = "ï¨¶  "

[nim]
symbol = "ïš¤  "

[nix_shell]
symbol = "ïŒ“  "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ  "

[rlang]
symbol = "ï³’  "

[ruby]
symbol = "î‘ "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[spack]
symbol = "ğŸ…¢ "

[container]
disabled = true
